name: Java Microservices CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        module: [module1, module2, ...] # Add more modules
      fail-fast: false
      max-parallel: 3

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11' # Use your desired Java version

      - name: Build and test
        run: |
          cd ${{ matrix.module }}
         mvn clean package -Dmaven.test.skip=true
      # - name: Build and push Docker image
      #   env:
      #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #   run: |
      #     echo "Building Docker image for ${{ matrix.module}}"
      #     docker build -t yourusername/${{ matrix.module }}:${{ github.run_number }} .
      #     echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      #     docker push yourusername/${{ matrix.module }}:${{ github.run_number }}
