name: build docker images Microservices

on:
  push:
    branches:  [ "build_test_ci" ]

  pull_request:
    branches: none # [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        module: [ts-admin-basic-info-service]
      fail-fast: false
      max-parallel: 3


    runs-on: ubuntu-latest
   

    steps:

      - name: Set Date
        id: set_date
        run:  echo "IMAGE_TAG=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build packages
        run: mvn clean package -Dmaven.test.skip=true
                   
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.module}}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.module }}:${{ env.IMAGE_TAG }}
     
      # - name: Build Docker Image
      #   working-directory: .
     #    run:
    #      docker build  --file ./src/Dockerfile --tag $DOCKER_REPOSITORY/$IMAGE_NAME:$GITHUB_RUN_NUMBER --build-arg=token=ZGEzNTQ5Y2QyNjAx --no-cache
        
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
         image-ref: 'docker.io/ ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.module }}:${{ env.IMAGE_TAG }}'
         format: 'table'
         exit-code: '1'
         ignore-unfixed: true
         vuln-type: 'os,library'
         severity: 'MEDIUM,HIGH,CRITICAL'
            
      - name: Run
        uses: tj-actions/docker-run@v2
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.module }}:${{ env.IMAGE_TAG }}
          name: ${{ matrix.module }}
          args: |
            echo "Hello World"
            uname -a